FROM golang:1.24.5 AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

# Compilar binário estático (sem dependência de libc)
RUN CGO_ENABLED=0 GOOS=linux go build -o client ./client

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/client .

EXPOSE 8080

CMD ["./client"]
